apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
